# Testing different hyperparamters for SAKT to achive the best AUC possible

## Clone the repo

In [4]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content
!git clone https://github.com/aarushban-12/knowledge-tracing-collection-pytorch.git
%cd knowledge-tracing-collection-pytorch

!pip install -r requirements.txt

!grep -n "learning_rate\|hidden_size\|num_epochs\|batch_size" train.py
!grep -n "hidden_size\|embed\|d_model" models/sakt.py

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content
fatal: destination path 'knowledge-tracing-collection-pytorch' already exists and is not an empty directory.
/content/knowledge-tracing-collection-pytorch
Requirement already satisfied: jupyter in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (7.17.1)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (6.17.1)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (7.7.1)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (from jupyter->-r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 4)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 4)) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 5)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 5)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (6.5.7)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->-r requirements.txt (line 1)) (5.7.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->-r requirements.txt (line 1)) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->-r requirements.txt (line 1)) (3.0.16)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter->-r requirements.txt (line 1)) (5.9.1)
Requirement already satisfied: prompt-toolkit>=3.0.30 in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter->-r requirements.txt (line 1)) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter->-r requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (1.2.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->-r requirements.txt (line 1)) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter->-r requirements.txt (line 1)) (6.4.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (3.3.3)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (0.10.4)
Requirement already satisfied: nbformat>=5.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->-r requirements.txt (line 1)) (25.1.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->-r requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->-r requirements.txt (line 1)) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter->-r requirements.txt (line 1)) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (0.20.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter->-r requirements.txt (line 1)) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-console->jupyter->-r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.5.4)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook->jupyter->-r requirements.txt (line 1)) (25.1.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (4.26.0)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2.32.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert->jupyter->-r requirements.txt (line 1)) (2.21.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter->-r requirements.txt (line 1)) (0.8.2)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook->jupyter->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert->jupyter->-r requirements.txt (line 1)) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert->jupyter->-r requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter->-r requirements.txt (line 1)) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2026.6.3)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter->-r requirements.txt (line 1)) (3.0)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->-r requirements.txt (line 1)) (1.4.0)
40:    batch_size = train_config["batch_size"]
41:    num_epochs = train_config["num_epochs"]
43:    learning_rate = train_config["learning_rate"]
109:        train_dataset, batch_size=batch_size, shuffle=True,
113:        test_dataset, batch_size=test_size, shuffle=True,
118:        opt = SGD(model.parameters(), learning_rate, momentum=0.9)
120:        opt = Adam(model.parameters(), learning_rate)
124:            train_loader, test_loader, num_epochs, opt, ckpt_path

## Import dataset

In [3]:
import os

os.makedirs("datasets/ASSIST2009", exist_ok=True)

import shutil

source = "/content/drive/MyDrive/education-ml-research/ASSISTments2009/skill_builder_data.csv"
destination = "/content/knowledge-tracing-collection-pytorch/datasets/ASSIST2009/skill_builder_data.csv"

shutil.copy2(source, destination)

print("Copied:", os.path.exists(destination))

import pandas as pd

path = "datasets/ASSIST2009/skill_builder_data.csv"

## Dataset only works in latin1, so first read in latin1 then convert to utf-8 to be used by SAKT
df = pd.read_csv(path, encoding="latin-1")

print(df.shape)
print(df.columns.tolist())

df.to_csv(
    "datasets/ASSIST2009/skill_builder_data_utf8.csv",
    index=False,
    encoding="utf-8"
)

!mv datasets/ASSIST2009/skill_builder_data.csv datasets/ASSIST2009/skill_builder_data_original.csv
!mv datasets/ASSIST2009/skill_builder_data_utf8.csv datasets/ASSIST2009/skill_builder_data.csv

pd.read_csv(
    "datasets/ASSIST2009/skill_builder_data.csv"
).head()

Copied: True

/tmp/ipykernel_36897/3498793680.py:19: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding="latin-1")

(525534, 30)
['order_id', 'assignment_id', 'user_id', 'assistment_id', 'problem_id', 'original', 'correct', 'attempt_count', 'ms_first_response', 'tutor_mode', 'answer_type', 'sequence_id', 'student_class_id', 'position', 'type', 'base_sequence_id', 'skill_id', 'skill_name', 'teacher_id', 'school_id', 'hint_count', 'hint_total', 'overlap_time', 'template_id', 'answer_id', 'answer_text', 'first_action', 'bottom_hint', 'opportunity', 'opportunity_original']

/tmp/ipykernel_36897/3498793680.py:33: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(

,order_id,assignment_id,user_id,assistment_id,problem_id,original,correct,attempt_count,ms_first_response,tutor_mode,...,hint_count,hint_total,overlap_time,template_id,answer_id,answer_text,first_action,bottom_hint,opportunity,opportunity_original
0,33022537,277618,64525,33139,51424,1,1,1,32454,tutor,...,0,3,32454,30799,NaN,26,0,NaN,1,1.0
1,33022709,277618,64525,33150,51435,1,1,1,4922,tutor,...,0,3,4922,30799,NaN,55,0,NaN,2,2.0
2,35450204,220674,70363,33159,51444,1,0,2,25390,tutor,...,0,3,42000,30799,NaN,88,0,NaN,1,1.0
3,35450295,220674,70363,33110,51395,1,1,1,4859,tutor,...,0,3,4859,30059,NaN,41,0,NaN,2,2.0
4,35450311,220674,70363,33196,51481,1,0,14,19813,tutor,...,3,4,124564,30060,NaN,65,0,0.0,3,3.0

## Set up 6 experiments with different hyperparameters

In [35]:
import os
import json
import pickle
import pandas as pd

REPO_DIR = "/content/knowledge-tracing-collection-pytorch"
CONFIG_PATH = os.path.join(REPO_DIR, "config.json")

%cd /content/knowledge-tracing-collection-pytorch

# Save original config
with open(CONFIG_PATH, "r") as f:
    original_config = json.load(f)

# Six experiments
experiments = [
    {"learning_rate": 0.001, "d": 65},
    {"learning_rate": 0.001, "d": 125},
    {"learning_rate": 0.0005, "d": 65},
    {"learning_rate": 0.0005, "d": 125},
    {"learning_rate": 0.0001, "d": 65},
    {"learning_rate": 0.0001, "d": 125},
]

# Results saved to Drive
RESULTS_PATH = (
    "/content/drive/MyDrive/"
    "education-ml-research/"
    "sakt_hyperparameter_results.csv"
)

results = []

print("Setup complete.")

/content/knowledge-tracing-collection-pytorch
Setup complete.

## Run the experiments

In [36]:
import subprocess

try:

    for i, exp in enumerate(experiments, start=1):

        lr = exp["learning_rate"]
        d = exp["d"]

        print("\n" + "=" * 70)
        print(f"EXPERIMENT {i}/6")
        print(f"Learning rate: {lr}")
        print(f"Embedding dimension (d): {d}")
        print("=" * 70)

        # Start from the original config
        config = json.loads(json.dumps(original_config))

        config["train_config"]["learning_rate"] = lr
        config["sakt"]["d"] = d

        # Write configuration
        with open(CONFIG_PATH, "w") as f:
            json.dump(config, f, indent=4)

        # Run training
        process = subprocess.Popen(
            [
                "python",
                "-u",
                "train.py",
                "--model_name=sakt",
                "--dataset_name=ASSIST2009"
            ],
            cwd=REPO_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )

        for line in process.stdout:
            print(line, end="", flush=True)

        process.wait()

        print(f"\nReturn code: {process.returncode}")

        # If training exits abnormally, stop the entire experiment loop
        if process.returncode != 0:
            raise RuntimeError(
                f"Experiment {i} failed with exit code "
                f"{process.returncode}"
            )

        # Load AUC history
        auc_path = os.path.join(
            REPO_DIR,
            "ckpts",
            "sakt",
            "ASSIST2009",
            "aucs.pkl"
        )

        if not os.path.exists(auc_path):
            raise FileNotFoundError(
                f"aucs.pkl was not created for experiment {i}"
            )

        with open(auc_path, "rb") as f:
            aucs = pickle.load(f)

        # Calculate results
        best_auc = max(aucs)
        best_epoch = aucs.index(best_auc) + 1
        final_auc = aucs[-1]

        result = {
            "Experiment": i,
            "Learning Rate": lr,
            "d": d,
            "Best AUC": best_auc,
            "Best Epoch": best_epoch,
            "Final AUC": final_auc
        }

        results.append(result)

        # Display results immediately
        results_df = pd.DataFrame(results)

        print("\nExperiment completed.")
        print(f"Best AUC:   {best_auc:.6f}")
        print(f"Best Epoch: {best_epoch}")
        print(f"Final AUC:  {final_auc:.6f}")

        display(results_df)

        # Save after EVERY experiment
        results_df.to_csv(
            RESULTS_PATH,
            index=False
        )

        print(f"Results saved to: {RESULTS_PATH}")

except KeyboardInterrupt:
    print("\nTraining interrupted.")
    print("The experiment loop has stopped completely.")
    print("No additional configurations will be started.")

except Exception as e:
    print(f"\nExperiment stopped because of an error:")
    print(e)

finally:
    # Always restore the original config
    with open(CONFIG_PATH, "w") as f:
        json.dump(original_config, f, indent=4)

    print("\nOriginal config.json restored.")

======================================================================
EXPERIMENT 1/6
Learning rate: 0.001
Embedding dimension (d): 65
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.7087352308458417,   Loss Mean: 0.6262502670288086
Epoch: 2,   AUC: 0.7614535836057177,   Loss Mean: 0.5597079992294312
Epoch: 3,   AUC: 0.7780138348928661,   Loss Mean: 0.5352844595909119
Epoch: 4,   AUC: 0.7865180529618282,   Loss Mean: 0.5239111185073853
Epoch: 5,   AUC: 0.7907121506585186,   Loss Mean: 0.5175146460533142
Epoch: 6,   AUC: 0.7947051530542038,   Loss Mean: 0.512439489364624
Epoch: 7,   AUC: 0.796548261909928,   Loss Mean: 0.5086390376091003
Epoch: 8,   AUC: 0.7985596492695662,   Loss Mean: 0.5072037577629089
Epoch: 9,   AUC: 0.7997873325792233,   Loss Mean: 0.5039315819740295
Epoch: 10,   AUC: 0.8004743538343815,   Loss Mean: 0.5021867752075195
Epoch: 11,   AUC: 0.8015767859238894,   Loss Mean: 0.5003129243850708
Epoch: 12,   AUC: 0.8018369160272021,   Loss Mean: 0.49829697608947754
Epoch: 13,   AUC: 0.8033024039722425,   Loss Mean: 0.49779731035232544
Epoch: 14,   AUC: 0.8034948253674298,   Loss Mean: 0.49598145484924316
Epoch: 15,   AUC: 0.8040603842595238,   Loss Mean: 0.49475371837615967
Epoch: 16,   AUC: 0.8044317184255414,   Loss Mean: 0.49423348903656006
Epoch: 17,   AUC: 0.8048630426609685,   Loss Mean: 0.49211087822914124
Epoch: 18,   AUC: 0.8046366750591125,   Loss Mean: 0.4920397400856018
Epoch: 19,   AUC: 0.8054698552007536,   Loss Mean: 0.491163045167923
Epoch: 20,   AUC: 0.8060894787883917,   Loss Mean: 0.48980849981307983
Epoch: 21,   AUC: 0.8063410014217435,   Loss Mean: 0.48897385597229004
Epoch: 22,   AUC: 0.8064447591320877,   Loss Mean: 0.4883173406124115
Epoch: 23,   AUC: 0.8067278382944463,   Loss Mean: 0.48710569739341736
Epoch: 24,   AUC: 0.8063304164784183,   Loss Mean: 0.48626211285591125
Epoch: 25,   AUC: 0.8068832433410655,   Loss Mean: 0.48598501086235046
Epoch: 26,   AUC: 0.8070071608110451,   Loss Mean: 0.4849601686000824
Epoch: 27,   AUC: 0.8069345388692768,   Loss Mean: 0.48427528142929077
Epoch: 28,   AUC: 0.8071755445050669,   Loss Mean: 0.483366996049881
Epoch: 29,   AUC: 0.8066571067548051,   Loss Mean: 0.48322829604148865
Epoch: 30,   AUC: 0.8070133192137139,   Loss Mean: 0.482521116733551
Epoch: 31,   AUC: 0.807139158793843,   Loss Mean: 0.48130378127098083
Epoch: 32,   AUC: 0.8067885053049797,   Loss Mean: 0.48147398233413696
Epoch: 33,   AUC: 0.8070706684577882,   Loss Mean: 0.4802338480949402
Epoch: 34,   AUC: 0.8075537849804519,   Loss Mean: 0.48004791140556335
Epoch: 35,   AUC: 0.8072332002600292,   Loss Mean: 0.47936517000198364
Epoch: 36,   AUC: 0.807370905686948,   Loss Mean: 0.47913047671318054
Epoch: 37,   AUC: 0.8073344560563765,   Loss Mean: 0.47838735580444336
Epoch: 38,   AUC: 0.8067686611156675,   Loss Mean: 0.47802549600601196
Epoch: 39,   AUC: 0.8066743685018081,   Loss Mean: 0.47671476006507874
Epoch: 40,   AUC: 0.8066592337088487,   Loss Mean: 0.47698724269866943
Epoch: 41,   AUC: 0.8073723582163779,   Loss Mean: 0.47633272409439087
Epoch: 42,   AUC: 0.8070446125158004,   Loss Mean: 0.47567641735076904
Epoch: 43,   AUC: 0.8071156863007684,   Loss Mean: 0.47544556856155396
Epoch: 44,   AUC: 0.8064813854216439,   Loss Mean: 0.4750007092952728
Epoch: 45,   AUC: 0.8067995427167586,   Loss Mean: 0.47430649399757385
Epoch: 46,   AUC: 0.8067930571678218,   Loss Mean: 0.47338607907295227
Epoch: 47,   AUC: 0.8061268232898315,   Loss Mean: 0.47292226552963257
Epoch: 48,   AUC: 0.80655643982174,   Loss Mean: 0.47265318036079407
Epoch: 49,   AUC: 0.8066033908475129,   Loss Mean: 0.4723662734031677
Epoch: 50,   AUC: 0.8068515977276134,   Loss Mean: 0.4727400243282318
Epoch: 51,   AUC: 0.8062198541257006,   Loss Mean: 0.47101885080337524
Epoch: 52,   AUC: 0.8061965854699158,   Loss Mean: 0.4713069796562195
Epoch: 53,   AUC: 0.8066066079535816,   Loss Mean: 0.4710133969783783
Epoch: 54,   AUC: 0.8059969004209763,   Loss Mean: 0.47045594453811646
Epoch: 55,   AUC: 0.806252669916188,   Loss Mean: 0.47008559107780457
Epoch: 56,   AUC: 0.8063489445331293,   Loss Mean: 0.46978476643562317
Epoch: 57,   AUC: 0.8061258101430048,   Loss Mean: 0.4689030647277832
Epoch: 58,   AUC: 0.8063533660407662,   Loss Mean: 0.46878036856651306
Epoch: 59,   AUC: 0.805818078244497,   Loss Mean: 0.4683290719985962
Epoch: 60,   AUC: 0.8055491141853457,   Loss Mean: 0.46819090843200684
Epoch: 61,   AUC: 0.8054247965903154,   Loss Mean: 0.4673674702644348
Epoch: 62,   AUC: 0.8053416148703194,   Loss Mean: 0.4674208164215088
Epoch: 63,   AUC: 0.8056025115025031,   Loss Mean: 0.4669592082500458
Epoch: 64,   AUC: 0.8053159907614055,   Loss Mean: 0.46655723452568054
Epoch: 65,   AUC: 0.8054358491011526,   Loss Mean: 0.46594542264938354
Epoch: 66,   AUC: 0.8049577706310153,   Loss Mean: 0.46560347080230713
Epoch: 67,   AUC: 0.8050902029633968,   Loss Mean: 0.4649970233440399
Epoch: 68,   AUC: 0.8046821237285627,   Loss Mean: 0.46525025367736816
Epoch: 69,   AUC: 0.8048972707167297,   Loss Mean: 0.4654286801815033
Epoch: 70,   AUC: 0.8048239416357207,   Loss Mean: 0.4644056558609009
Epoch: 71,   AUC: 0.804434642106573,   Loss Mean: 0.4643791913986206
Epoch: 72,   AUC: 0.8043413918310534,   Loss Mean: 0.46334436535835266
Epoch: 73,   AUC: 0.8043529712990332,   Loss Mean: 0.46251755952835083
Epoch: 74,   AUC: 0.8042099132558684,   Loss Mean: 0.4626469612121582
Epoch: 75,   AUC: 0.8037813501349429,   Loss Mean: 0.46279677748680115
Epoch: 76,   AUC: 0.8043115087810326,   Loss Mean: 0.46224501729011536
Epoch: 77,   AUC: 0.8038041512232155,   Loss Mean: 0.4619426131248474
Epoch: 78,   AUC: 0.8032839176915935,   Loss Mean: 0.4623486399650574
Epoch: 79,   AUC: 0.8033761100264125,   Loss Mean: 0.46141916513442993
Epoch: 80,   AUC: 0.8038208195772186,   Loss Mean: 0.4612168073654175
Epoch: 81,   AUC: 0.8033574108490383,   Loss Mean: 0.46066635847091675
Epoch: 82,   AUC: 0.8036173008773205,   Loss Mean: 0.46100014448165894
Epoch: 83,   AUC: 0.8030684999269768,   Loss Mean: 0.4602768123149872
Epoch: 84,   AUC: 0.802973169504495,   Loss Mean: 0.45983994007110596
Epoch: 85,   AUC: 0.8029449257089277,   Loss Mean: 0.45918571949005127
Epoch: 86,   AUC: 0.803412202815901,   Loss Mean: 0.45838820934295654
Epoch: 87,   AUC: 0.8030536711416034,   Loss Mean: 0.4592469036579132
Epoch: 88,   AUC: 0.8031768200695043,   Loss Mean: 0.4581976532936096
Epoch: 89,   AUC: 0.802522816428916,   Loss Mean: 0.4583246409893036
Epoch: 90,   AUC: 0.8019525556899985,   Loss Mean: 0.45747217535972595
Epoch: 91,   AUC: 0.8020323174732393,   Loss Mean: 0.4583130478858948
Epoch: 92,   AUC: 0.8023943541423216,   Loss Mean: 0.4575389325618744
Epoch: 93,   AUC: 0.8022556028539493,   Loss Mean: 0.45776495337486267
Epoch: 94,   AUC: 0.801943790686527,   Loss Mean: 0.45712926983833313
Epoch: 95,   AUC: 0.8017572966784133,   Loss Mean: 0.4564025104045868
Epoch: 96,   AUC: 0.8018722417845177,   Loss Mean: 0.4570293426513672
Epoch: 97,   AUC: 0.8024130704319621,   Loss Mean: 0.4566001296043396
Epoch: 98,   AUC: 0.8013129948021873,   Loss Mean: 0.45553427934646606
Epoch: 99,   AUC: 0.8016898215023929,   Loss Mean: 0.45552536845207214
Epoch: 100,   AUC: 0.8012937515554044,   Loss Mean: 0.4551108777523041

Return code: 0

Experiment completed.
Best AUC:   0.807554
Best Epoch: 34
Final AUC:  0.801294

   Experiment  Learning Rate   d  Best AUC  Best Epoch  Final AUC
0           1          0.001  65  0.807554          34   0.801294

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

======================================================================
EXPERIMENT 2/6
Learning rate: 0.001
Embedding dimension (d): 125
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.7583082307794542,   Loss Mean: 0.5980345606803894
Epoch: 2,   AUC: 0.7871008418929024,   Loss Mean: 0.5308004021644592
Epoch: 3,   AUC: 0.7962368891251088,   Loss Mean: 0.5138627886772156
Epoch: 4,   AUC: 0.8004135464026039,   Loss Mean: 0.5070104002952576
Epoch: 5,   AUC: 0.8021430579948475,   Loss Mean: 0.5014625191688538
Epoch: 6,   AUC: 0.8045860041286221,   Loss Mean: 0.49812889099121094
Epoch: 7,   AUC: 0.8058269559876052,   Loss Mean: 0.494830846786499
Epoch: 8,   AUC: 0.8055919436714443,   Loss Mean: 0.49336403608322144
Epoch: 9,   AUC: 0.8069503118491098,   Loss Mean: 0.4910041093826294
Epoch: 10,   AUC: 0.8067225480876425,   Loss Mean: 0.48939698934555054
Epoch: 11,   AUC: 0.8066682709986754,   Loss Mean: 0.4871055483818054
Epoch: 12,   AUC: 0.8073321906942965,   Loss Mean: 0.48605895042419434
Epoch: 13,   AUC: 0.807182618917286,   Loss Mean: 0.4842754304409027
Epoch: 14,   AUC: 0.8075951936451438,   Loss Mean: 0.48340341448783875
Epoch: 15,   AUC: 0.8081620455199491,   Loss Mean: 0.48153093457221985
Epoch: 16,   AUC: 0.8082399375364432,   Loss Mean: 0.4811815023422241
Epoch: 17,   AUC: 0.8079747185471069,   Loss Mean: 0.47915077209472656
Epoch: 18,   AUC: 0.8081278602448536,   Loss Mean: 0.4781283438205719
Epoch: 19,   AUC: 0.8086074264755574,   Loss Mean: 0.4761824607849121
Epoch: 20,   AUC: 0.8080986631953918,   Loss Mean: 0.47480031847953796
Epoch: 21,   AUC: 0.8078613427364847,   Loss Mean: 0.47477415204048157
Epoch: 22,   AUC: 0.8078667411532079,   Loss Mean: 0.47282227873802185
Epoch: 23,   AUC: 0.8082106448596105,   Loss Mean: 0.47175973653793335
Epoch: 24,   AUC: 0.8079286623922024,   Loss Mean: 0.4707079231739044
Epoch: 25,   AUC: 0.8077904647359757,   Loss Mean: 0.4694547951221466
Epoch: 26,   AUC: 0.8074156769119725,   Loss Mean: 0.46904709935188293
Epoch: 27,   AUC: 0.807125806193091,   Loss Mean: 0.46740293502807617
Epoch: 28,   AUC: 0.8072937036974285,   Loss Mean: 0.4671173691749573
Epoch: 29,   AUC: 0.8068805375897786,   Loss Mean: 0.46603721380233765
Epoch: 30,   AUC: 0.806498025087436,   Loss Mean: 0.46437597274780273
Epoch: 31,   AUC: 0.8058926907454802,   Loss Mean: 0.46335074305534363
Epoch: 32,   AUC: 0.8056384482683869,   Loss Mean: 0.46287354826927185
Epoch: 33,   AUC: 0.8062805407650099,   Loss Mean: 0.4620002210140228
Epoch: 34,   AUC: 0.8066136662601382,   Loss Mean: 0.4609122574329376
Epoch: 35,   AUC: 0.8050879914546254,   Loss Mean: 0.4596077501773834
Epoch: 36,   AUC: 0.8046740235869683,   Loss Mean: 0.45963555574417114
Epoch: 37,   AUC: 0.8051615263861323,   Loss Mean: 0.4583949148654938
Epoch: 38,   AUC: 0.8039254817211684,   Loss Mean: 0.45721304416656494
Epoch: 39,   AUC: 0.8047275829673537,   Loss Mean: 0.4566425383090973
Epoch: 40,   AUC: 0.8039651102068605,   Loss Mean: 0.456025630235672
Epoch: 41,   AUC: 0.8044691021845334,   Loss Mean: 0.45509833097457886
Epoch: 42,   AUC: 0.8032493202122005,   Loss Mean: 0.45421844720840454
Epoch: 43,   AUC: 0.8027553212947587,   Loss Mean: 0.45401620864868164
Epoch: 44,   AUC: 0.80184698307282,   Loss Mean: 0.4532826244831085
Epoch: 45,   AUC: 0.8028987608408019,   Loss Mean: 0.45145028829574585
Epoch: 46,   AUC: 0.8016412025339554,   Loss Mean: 0.44996359944343567
Epoch: 47,   AUC: 0.8024496066304694,   Loss Mean: 0.4494413137435913
Epoch: 48,   AUC: 0.8014627528009197,   Loss Mean: 0.4496036469936371
Epoch: 49,   AUC: 0.8007842494279751,   Loss Mean: 0.44901061058044434
Epoch: 50,   AUC: 0.8015942092308187,   Loss Mean: 0.44810035824775696
Epoch: 51,   AUC: 0.7999975361356306,   Loss Mean: 0.44559404253959656
Epoch: 52,   AUC: 0.7994490185442852,   Loss Mean: 0.44652479887008667
Epoch: 53,   AUC: 0.8001078433142593,   Loss Mean: 0.4452279806137085
Epoch: 54,   AUC: 0.7988752840153039,   Loss Mean: 0.444435715675354
Epoch: 55,   AUC: 0.7986742018001493,   Loss Mean: 0.4437379240989685
Epoch: 56,   AUC: 0.7990142919876713,   Loss Mean: 0.4426072835922241
Epoch: 57,   AUC: 0.7982157888471316,   Loss Mean: 0.4423372745513916
Epoch: 58,   AUC: 0.7988564610256499,   Loss Mean: 0.4409324526786804
Epoch: 59,   AUC: 0.7980061353997564,   Loss Mean: 0.44077545404434204
Epoch: 60,   AUC: 0.7973832015951885,   Loss Mean: 0.44001373648643494
Epoch: 61,   AUC: 0.7968206373497011,   Loss Mean: 0.43918663263320923
Epoch: 62,   AUC: 0.7972623678562609,   Loss Mean: 0.43864989280700684
Epoch: 63,   AUC: 0.79597418765213,   Loss Mean: 0.43757155537605286
Epoch: 64,   AUC: 0.7964377554237267,   Loss Mean: 0.4374740421772003
Epoch: 65,   AUC: 0.7963600214440454,   Loss Mean: 0.4370429813861847
Epoch: 66,   AUC: 0.7955740324032077,   Loss Mean: 0.4361933767795563
Epoch: 67,   AUC: 0.7966716282642715,   Loss Mean: 0.43470335006713867
Epoch: 68,   AUC: 0.7950279754550993,   Loss Mean: 0.4346961975097656
Epoch: 69,   AUC: 0.7949739037133281,   Loss Mean: 0.4347545802593231
Epoch: 70,   AUC: 0.7943668098277525,   Loss Mean: 0.4337979853153229
Epoch: 71,   AUC: 0.7946735738766091,   Loss Mean: 0.4327743649482727
Epoch: 72,   AUC: 0.7941096532323646,   Loss Mean: 0.4321933090686798
Epoch: 73,   AUC: 0.7940594790608994,   Loss Mean: 0.43165281414985657
Epoch: 74,   AUC: 0.7928218052075212,   Loss Mean: 0.4312613010406494
Epoch: 75,   AUC: 0.7933574045476979,   Loss Mean: 0.43046149611473083
Epoch: 76,   AUC: 0.7933066490624797,   Loss Mean: 0.42907723784446716
Epoch: 77,   AUC: 0.7933126886858881,   Loss Mean: 0.4288635849952698
Epoch: 78,   AUC: 0.7921063634978109,   Loss Mean: 0.428558349609375
Epoch: 79,   AUC: 0.7925114193978272,   Loss Mean: 0.42795759439468384
Epoch: 80,   AUC: 0.7926475781778517,   Loss Mean: 0.42744889855384827
Epoch: 81,   AUC: 0.7916097292913553,   Loss Mean: 0.4269576370716095
Epoch: 82,   AUC: 0.7916644679082114,   Loss Mean: 0.42510467767715454
Epoch: 83,   AUC: 0.792188205428014,   Loss Mean: 0.42580604553222656
Epoch: 84,   AUC: 0.7906581418294911,   Loss Mean: 0.4253912568092346
Epoch: 85,   AUC: 0.7921139970784972,   Loss Mean: 0.4239802658557892
Epoch: 86,   AUC: 0.7917921128324378,   Loss Mean: 0.42470261454582214
Epoch: 87,   AUC: 0.7898873243226554,   Loss Mean: 0.4241867959499359
Epoch: 88,   AUC: 0.789310193512111,   Loss Mean: 0.42322447896003723
Epoch: 89,   AUC: 0.7905330451230412,   Loss Mean: 0.4228031039237976
Epoch: 90,   AUC: 0.7903158642916914,   Loss Mean: 0.4219692051410675
Epoch: 91,   AUC: 0.7896715849480924,   Loss Mean: 0.4213951826095581
Epoch: 92,   AUC: 0.790687953913937,   Loss Mean: 0.4213965833187103
Epoch: 93,   AUC: 0.7900508375637003,   Loss Mean: 0.420915812253952
Epoch: 94,   AUC: 0.7893705952825162,   Loss Mean: 0.41968750953674316
Epoch: 95,   AUC: 0.7889799499239523,   Loss Mean: 0.41992560029029846
Epoch: 96,   AUC: 0.7890070119665393,   Loss Mean: 0.4192034900188446
Epoch: 97,   AUC: 0.7878494975049429,   Loss Mean: 0.41848626732826233
Epoch: 98,   AUC: 0.7884532363797151,   Loss Mean: 0.41866907477378845
Epoch: 99,   AUC: 0.787985773554322,   Loss Mean: 0.4178493320941925
Epoch: 100,   AUC: 0.7877711313780115,   Loss Mean: 0.41757652163505554

Return code: 0

Experiment completed.
Best AUC:   0.808607
Best Epoch: 19
Final AUC:  0.787771

   Experiment  Learning Rate    d  Best AUC  Best Epoch  Final AUC
0           1          0.001   65  0.807554          34   0.801294
1           2          0.001  125  0.808607          19   0.787771

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

======================================================================
EXPERIMENT 3/6
Learning rate: 0.0005
Embedding dimension (d): 65
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.6141551646333697,   Loss Mean: 0.6583130359649658
Epoch: 2,   AUC: 0.7054300851865529,   Loss Mean: 0.6061605215072632
Epoch: 3,   AUC: 0.7411127147899458,   Loss Mean: 0.572497546672821
Epoch: 4,   AUC: 0.7613522311753957,   Loss Mean: 0.5516953468322754
Epoch: 5,   AUC: 0.772875983629174,   Loss Mean: 0.5385340452194214
Epoch: 6,   AUC: 0.7805092336460366,   Loss Mean: 0.5302847623825073
Epoch: 7,   AUC: 0.7850490454262463,   Loss Mean: 0.5244801640510559
Epoch: 8,   AUC: 0.788486659655657,   Loss Mean: 0.521003007888794
Epoch: 9,   AUC: 0.7912471133217278,   Loss Mean: 0.5174100399017334
Epoch: 10,   AUC: 0.7929591059796718,   Loss Mean: 0.5144491195678711
Epoch: 11,   AUC: 0.7949061054174551,   Loss Mean: 0.5124228000640869
Epoch: 12,   AUC: 0.7958043408593376,   Loss Mean: 0.510068953037262
Epoch: 13,   AUC: 0.7973025268222091,   Loss Mean: 0.5086213946342468
Epoch: 14,   AUC: 0.7980475219191624,   Loss Mean: 0.5068209171295166
Epoch: 15,   AUC: 0.7992168790756586,   Loss Mean: 0.5055660605430603
Epoch: 16,   AUC: 0.7997787235993565,   Loss Mean: 0.5048148036003113
Epoch: 17,   AUC: 0.8004958246955981,   Loss Mean: 0.5029610395431519
Epoch: 18,   AUC: 0.8010531022573955,   Loss Mean: 0.5024930238723755
Epoch: 19,   AUC: 0.8015448891627639,   Loss Mean: 0.5015507340431213
Epoch: 20,   AUC: 0.8024902170582673,   Loss Mean: 0.50091552734375
Epoch: 21,   AUC: 0.802547990082584,   Loss Mean: 0.4996071457862854
Epoch: 22,   AUC: 0.8027833320615227,   Loss Mean: 0.49852362275123596
Epoch: 23,   AUC: 0.8037288577546928,   Loss Mean: 0.49813902378082275
Epoch: 24,   AUC: 0.8038084464020625,   Loss Mean: 0.49717339873313904
Epoch: 25,   AUC: 0.8040247248130148,   Loss Mean: 0.49622583389282227
Epoch: 26,   AUC: 0.8043977661792492,   Loss Mean: 0.49591270089149475
Epoch: 27,   AUC: 0.8044983807689113,   Loss Mean: 0.49498865008354187
Epoch: 28,   AUC: 0.8050109641108827,   Loss Mean: 0.4943193793296814
Epoch: 29,   AUC: 0.8053335076824977,   Loss Mean: 0.49325326085090637
Epoch: 30,   AUC: 0.8055848154059164,   Loss Mean: 0.49306273460388184
Epoch: 31,   AUC: 0.8057903754985266,   Loss Mean: 0.49234917759895325
Epoch: 32,   AUC: 0.8057240876118079,   Loss Mean: 0.4922601878643036
Epoch: 33,   AUC: 0.8061852143689437,   Loss Mean: 0.49110299348831177
Epoch: 34,   AUC: 0.8062509601994615,   Loss Mean: 0.49084123969078064
Epoch: 35,   AUC: 0.8064943238048905,   Loss Mean: 0.48988303542137146
Epoch: 36,   AUC: 0.8063962483735696,   Loss Mean: 0.48960068821907043
Epoch: 37,   AUC: 0.8065348451482433,   Loss Mean: 0.48964548110961914
Epoch: 38,   AUC: 0.8064140974739493,   Loss Mean: 0.4884283244609833
Epoch: 39,   AUC: 0.8068043935409593,   Loss Mean: 0.4881533980369568
Epoch: 40,   AUC: 0.8071212789920446,   Loss Mean: 0.48847097158432007
Epoch: 41,   AUC: 0.807226749438927,   Loss Mean: 0.4875130355358124
Epoch: 42,   AUC: 0.8072669320600669,   Loss Mean: 0.4869322180747986
Epoch: 43,   AUC: 0.8072291018722446,   Loss Mean: 0.48713698983192444
Epoch: 44,   AUC: 0.8068072915535915,   Loss Mean: 0.4858803451061249
Epoch: 45,   AUC: 0.8076031800404974,   Loss Mean: 0.48577645421028137
Epoch: 46,   AUC: 0.8076465088021311,   Loss Mean: 0.48526763916015625
Epoch: 47,   AUC: 0.8073400135165162,   Loss Mean: 0.4852745831012726
Epoch: 48,   AUC: 0.8075122248218731,   Loss Mean: 0.484483927488327
Epoch: 49,   AUC: 0.807531774076242,   Loss Mean: 0.48422232270240784
Epoch: 50,   AUC: 0.8078610779996588,   Loss Mean: 0.48393988609313965
Epoch: 51,   AUC: 0.8078919450049931,   Loss Mean: 0.4830390214920044
Epoch: 52,   AUC: 0.807549955859211,   Loss Mean: 0.48276105523109436
Epoch: 53,   AUC: 0.8076827254038994,   Loss Mean: 0.4830041527748108
Epoch: 54,   AUC: 0.8075052878110865,   Loss Mean: 0.4823653995990753
Epoch: 55,   AUC: 0.8077791414486888,   Loss Mean: 0.48262321949005127
Epoch: 56,   AUC: 0.8076049340477955,   Loss Mean: 0.48166894912719727
Epoch: 57,   AUC: 0.8077361911701222,   Loss Mean: 0.4810549318790436
Epoch: 58,   AUC: 0.807767930901039,   Loss Mean: 0.4808768630027771
Epoch: 59,   AUC: 0.8078619602879782,   Loss Mean: 0.4805104732513428
Epoch: 60,   AUC: 0.8076987168167789,   Loss Mean: 0.4800310730934143
Epoch: 61,   AUC: 0.8077979317237163,   Loss Mean: 0.47994714975357056
Epoch: 62,   AUC: 0.8078451771811304,   Loss Mean: 0.4795899987220764
Epoch: 63,   AUC: 0.8079886645408587,   Loss Mean: 0.47946199774742126
Epoch: 64,   AUC: 0.8078728547620031,   Loss Mean: 0.47941696643829346
Epoch: 65,   AUC: 0.8076676132595277,   Loss Mean: 0.4786827862262726
Epoch: 66,   AUC: 0.8079012742099512,   Loss Mean: 0.47890618443489075
Epoch: 67,   AUC: 0.8078479005479855,   Loss Mean: 0.47781187295913696
Epoch: 68,   AUC: 0.8075220779641619,   Loss Mean: 0.4780477285385132
Epoch: 69,   AUC: 0.8078719825397225,   Loss Mean: 0.47824904322624207
Epoch: 70,   AUC: 0.8077648919638607,   Loss Mean: 0.47752976417541504
Epoch: 71,   AUC: 0.8077037412801529,   Loss Mean: 0.47689729928970337
Epoch: 72,   AUC: 0.8077489800726894,   Loss Mean: 0.4771237075328827
Epoch: 73,   AUC: 0.8076499055869963,   Loss Mean: 0.4766886234283447
Epoch: 74,   AUC: 0.8077005136047429,   Loss Mean: 0.4762445092201233
Epoch: 75,   AUC: 0.8074217764283129,   Loss Mean: 0.47638970613479614
Epoch: 76,   AUC: 0.8074409542458424,   Loss Mean: 0.47568076848983765
Epoch: 77,   AUC: 0.8074526721218587,   Loss Mean: 0.4748679995536804
Epoch: 78,   AUC: 0.8074199328332674,   Loss Mean: 0.4751841127872467
Epoch: 79,   AUC: 0.8075673172600003,   Loss Mean: 0.47515928745269775
Epoch: 80,   AUC: 0.8071850171510809,   Loss Mean: 0.4741494059562683
Epoch: 81,   AUC: 0.8074636234690038,   Loss Mean: 0.47455739974975586
Epoch: 82,   AUC: 0.8074525306940104,   Loss Mean: 0.47409963607788086
Epoch: 83,   AUC: 0.807402829123077,   Loss Mean: 0.4739372432231903
Epoch: 84,   AUC: 0.8073809747457737,   Loss Mean: 0.4738873243331909
Epoch: 85,   AUC: 0.8069950116052571,   Loss Mean: 0.4731275141239166
Epoch: 86,   AUC: 0.8073050939238746,   Loss Mean: 0.4735970199108124
Epoch: 87,   AUC: 0.8071393430023569,   Loss Mean: 0.4732324779033661
Epoch: 88,   AUC: 0.80739944995378,   Loss Mean: 0.47301048040390015
Epoch: 89,   AUC: 0.8074870501616009,   Loss Mean: 0.4719602167606354
Epoch: 90,   AUC: 0.8073317432588623,   Loss Mean: 0.47215500473976135
Epoch: 91,   AUC: 0.8071790042026759,   Loss Mean: 0.47166329622268677
Epoch: 92,   AUC: 0.8073868004658531,   Loss Mean: 0.47149497270584106
Epoch: 93,   AUC: 0.8071692708462515,   Loss Mean: 0.47158265113830566
Epoch: 94,   AUC: 0.8073195739209963,   Loss Mean: 0.47051313519477844
Epoch: 95,   AUC: 0.8068875757642571,   Loss Mean: 0.47038087248802185
Epoch: 96,   AUC: 0.8070608133022914,   Loss Mean: 0.4701985716819763
Epoch: 97,   AUC: 0.8072148428246795,   Loss Mean: 0.47038519382476807
Epoch: 98,   AUC: 0.8067265946353261,   Loss Mean: 0.4703218638896942
Epoch: 99,   AUC: 0.806936650724262,   Loss Mean: 0.46980246901512146
Epoch: 100,   AUC: 0.8070609949942957,   Loss Mean: 0.47036832571029663

Return code: 0

Experiment completed.
Best AUC:   0.807989
Best Epoch: 63
Final AUC:  0.807061

   Experiment  Learning Rate    d  Best AUC  Best Epoch  Final AUC
0           1         0.0010   65  0.807554          34   0.801294
1           2         0.0010  125  0.808607          19   0.787771
2           3         0.0005   65  0.807989          63   0.807061

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

======================================================================
EXPERIMENT 4/6
Learning rate: 0.0005
Embedding dimension (d): 125
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.7266000870929801,   Loss Mean: 0.6216321587562561
Epoch: 2,   AUC: 0.7702466280420133,   Loss Mean: 0.5495851039886475
Epoch: 3,   AUC: 0.7855640083798405,   Loss Mean: 0.5281078219413757
Epoch: 4,   AUC: 0.793207939470701,   Loss Mean: 0.5179629921913147
Epoch: 5,   AUC: 0.7972734269100237,   Loss Mean: 0.5109690427780151
Epoch: 6,   AUC: 0.7997506156953159,   Loss Mean: 0.5063858032226562
Epoch: 7,   AUC: 0.8013752376511283,   Loss Mean: 0.5034047961235046
Epoch: 8,   AUC: 0.8028261987919658,   Loss Mean: 0.501281201839447
Epoch: 9,   AUC: 0.8042468143482898,   Loss Mean: 0.4985654354095459
Epoch: 10,   AUC: 0.8048299183463852,   Loss Mean: 0.4972669780254364
Epoch: 11,   AUC: 0.8046956232934843,   Loss Mean: 0.4946765899658203
Epoch: 12,   AUC: 0.8052463896379454,   Loss Mean: 0.4938277304172516
Epoch: 13,   AUC: 0.8057818002398907,   Loss Mean: 0.4924720227718353
Epoch: 14,   AUC: 0.8063347911789738,   Loss Mean: 0.4909801483154297
Epoch: 15,   AUC: 0.8070491336772236,   Loss Mean: 0.4895156919956207
Epoch: 16,   AUC: 0.807450605564049,   Loss Mean: 0.48886337876319885
Epoch: 17,   AUC: 0.8079970379754127,   Loss Mean: 0.4873417615890503
Epoch: 18,   AUC: 0.8072566153766814,   Loss Mean: 0.4866236746311188
Epoch: 19,   AUC: 0.807941437202315,   Loss Mean: 0.48514097929000854
Epoch: 20,   AUC: 0.8085626471977017,   Loss Mean: 0.48424574732780457
Epoch: 21,   AUC: 0.8090148816159726,   Loss Mean: 0.48369818925857544
Epoch: 22,   AUC: 0.8089676195495942,   Loss Mean: 0.4824043810367584
Epoch: 23,   AUC: 0.8088850241763709,   Loss Mean: 0.4816133677959442
Epoch: 24,   AUC: 0.8089589828881203,   Loss Mean: 0.4806523323059082
Epoch: 25,   AUC: 0.8092689866916335,   Loss Mean: 0.4796978533267975
Epoch: 26,   AUC: 0.8089485967490656,   Loss Mean: 0.47913458943367004
Epoch: 27,   AUC: 0.8094172025731887,   Loss Mean: 0.47858595848083496
Epoch: 28,   AUC: 0.8093833177693579,   Loss Mean: 0.4772493541240692
Epoch: 29,   AUC: 0.8089928893339349,   Loss Mean: 0.4770585000514984
Epoch: 30,   AUC: 0.8091492692764324,   Loss Mean: 0.47617775201797485
Epoch: 31,   AUC: 0.8088472604244061,   Loss Mean: 0.4750748574733734
Epoch: 32,   AUC: 0.8087711526133274,   Loss Mean: 0.47529876232147217
Epoch: 33,   AUC: 0.809212608820324,   Loss Mean: 0.4736073911190033
Epoch: 34,   AUC: 0.8093230216923624,   Loss Mean: 0.47317323088645935
Epoch: 35,   AUC: 0.8091341772641388,   Loss Mean: 0.47248032689094543
Epoch: 36,   AUC: 0.8090249169535677,   Loss Mean: 0.4720832109451294
Epoch: 37,   AUC: 0.8091422426778987,   Loss Mean: 0.47135505080223083
Epoch: 38,   AUC: 0.8086962215222093,   Loss Mean: 0.4707942008972168
Epoch: 39,   AUC: 0.8089800264459809,   Loss Mean: 0.4698426127433777
Epoch: 40,   AUC: 0.808860737844042,   Loss Mean: 0.4702828824520111
Epoch: 41,   AUC: 0.8090185683027614,   Loss Mean: 0.4688173532485962
Epoch: 42,   AUC: 0.8085824239445525,   Loss Mean: 0.46848419308662415
Epoch: 43,   AUC: 0.8086752489299238,   Loss Mean: 0.4676206111907959
Epoch: 44,   AUC: 0.8078644013024391,   Loss Mean: 0.46718040108680725
Epoch: 45,   AUC: 0.8085914773400418,   Loss Mean: 0.46623343229293823
Epoch: 46,   AUC: 0.8082421611244613,   Loss Mean: 0.4654776155948639
Epoch: 47,   AUC: 0.807607870311376,   Loss Mean: 0.4653830826282501
Epoch: 48,   AUC: 0.8080539931340595,   Loss Mean: 0.4646289646625519
Epoch: 49,   AUC: 0.8077658864885152,   Loss Mean: 0.46417000889778137
Epoch: 50,   AUC: 0.8076656257201245,   Loss Mean: 0.46346771717071533
Epoch: 51,   AUC: 0.8076282384380188,   Loss Mean: 0.46239015460014343
Epoch: 52,   AUC: 0.8070291913440311,   Loss Mean: 0.46219590306282043
Epoch: 53,   AUC: 0.8072453182610961,   Loss Mean: 0.4620770215988159
Epoch: 54,   AUC: 0.8068692319180601,   Loss Mean: 0.461262047290802
Epoch: 55,   AUC: 0.807014970044112,   Loss Mean: 0.4608609974384308
Epoch: 56,   AUC: 0.8066128197062572,   Loss Mean: 0.45923393964767456
Epoch: 57,   AUC: 0.8065178994748652,   Loss Mean: 0.4599861204624176
Epoch: 58,   AUC: 0.8062762999427734,   Loss Mean: 0.45908278226852417
Epoch: 59,   AUC: 0.8060498850305341,   Loss Mean: 0.45847511291503906
Epoch: 60,   AUC: 0.8057966934479137,   Loss Mean: 0.45804810523986816
Epoch: 61,   AUC: 0.8060175126490652,   Loss Mean: 0.4577999711036682
Epoch: 62,   AUC: 0.8059843425340043,   Loss Mean: 0.45751771330833435
Epoch: 63,   AUC: 0.8052885688579237,   Loss Mean: 0.45575615763664246
Epoch: 64,   AUC: 0.8053679129005455,   Loss Mean: 0.4562965929508209
Epoch: 65,   AUC: 0.8049852171962928,   Loss Mean: 0.45521751046180725
Epoch: 66,   AUC: 0.8054216318276493,   Loss Mean: 0.4554862380027771
Epoch: 67,   AUC: 0.8051486906764835,   Loss Mean: 0.4535703957080841
Epoch: 68,   AUC: 0.8048562168799132,   Loss Mean: 0.45402786135673523
Epoch: 69,   AUC: 0.8046512265251112,   Loss Mean: 0.4536992609500885
Epoch: 70,   AUC: 0.8042365490017034,   Loss Mean: 0.45232924818992615
Epoch: 71,   AUC: 0.8034889936077271,   Loss Mean: 0.45228761434555054
Epoch: 72,   AUC: 0.8035277986914278,   Loss Mean: 0.45186448097229004
Epoch: 73,   AUC: 0.8036914860749477,   Loss Mean: 0.4514279365539551
Epoch: 74,   AUC: 0.803463287460595,   Loss Mean: 0.450523316860199
Epoch: 75,   AUC: 0.8033279072886885,   Loss Mean: 0.4509815275669098
Epoch: 76,   AUC: 0.8029666557706493,   Loss Mean: 0.44970428943634033
Epoch: 77,   AUC: 0.802756084803818,   Loss Mean: 0.4488884508609772
Epoch: 78,   AUC: 0.8025668654156412,   Loss Mean: 0.44938772916793823
Epoch: 79,   AUC: 0.8020329627063401,   Loss Mean: 0.44725897908210754
Epoch: 80,   AUC: 0.8017437498031084,   Loss Mean: 0.44747763872146606
Epoch: 81,   AUC: 0.8016066020347508,   Loss Mean: 0.44668203592300415
Epoch: 82,   AUC: 0.8018436738624941,   Loss Mean: 0.44650474190711975
Epoch: 83,   AUC: 0.801901130309884,   Loss Mean: 0.4469280242919922
Epoch: 84,   AUC: 0.8006091456463077,   Loss Mean: 0.4466053545475006
Epoch: 85,   AUC: 0.8015389537228593,   Loss Mean: 0.4457167983055115
Epoch: 86,   AUC: 0.8014553668447931,   Loss Mean: 0.44565773010253906
Epoch: 87,   AUC: 0.8008032148520815,   Loss Mean: 0.4446820020675659
Epoch: 88,   AUC: 0.800835805666597,   Loss Mean: 0.44426482915878296
Epoch: 89,   AUC: 0.8002941415379142,   Loss Mean: 0.44330811500549316
Epoch: 90,   AUC: 0.7997208745764453,   Loss Mean: 0.4427340030670166
Epoch: 91,   AUC: 0.7997742522648266,   Loss Mean: 0.4423760771751404
Epoch: 92,   AUC: 0.8003450042264479,   Loss Mean: 0.44264838099479675
Epoch: 93,   AUC: 0.7994244040590843,   Loss Mean: 0.44287580251693726
Epoch: 94,   AUC: 0.7993555055451474,   Loss Mean: 0.4407157301902771
Epoch: 95,   AUC: 0.7994123535004789,   Loss Mean: 0.44033896923065186
Epoch: 96,   AUC: 0.7987959681575914,   Loss Mean: 0.44049665331840515
Epoch: 97,   AUC: 0.7989893694816766,   Loss Mean: 0.44086968898773193
Epoch: 98,   AUC: 0.7985824825691638,   Loss Mean: 0.44016367197036743
Epoch: 99,   AUC: 0.7986402022434737,   Loss Mean: 0.43917402625083923
Epoch: 100,   AUC: 0.7978546500687294,   Loss Mean: 0.43886467814445496

Return code: 0

Experiment completed.
Best AUC:   0.809417
Best Epoch: 27
Final AUC:  0.797855

   Experiment  Learning Rate    d  Best AUC  Best Epoch  Final AUC
0           1         0.0010   65  0.807554          34   0.801294
1           2         0.0010  125  0.808607          19   0.787771
2           3         0.0005   65  0.807989          63   0.807061
3           4         0.0005  125  0.809417          27   0.797855

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

======================================================================
EXPERIMENT 5/6
Learning rate: 0.0001
Embedding dimension (d): 65
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.552166911487499,   Loss Mean: 0.6642418503761292
Epoch: 2,   AUC: 0.5818145883246123,   Loss Mean: 0.6393423080444336
Epoch: 3,   AUC: 0.6112452277714318,   Loss Mean: 0.6281858086585999
Epoch: 4,   AUC: 0.6386428232789763,   Loss Mean: 0.6187676787376404
Epoch: 5,   AUC: 0.6630747845175108,   Loss Mean: 0.6095010042190552
Epoch: 6,   AUC: 0.6840783726537512,   Loss Mean: 0.6008458733558655
Epoch: 7,   AUC: 0.7011118963807098,   Loss Mean: 0.5915141105651855
Epoch: 8,   AUC: 0.7147911189600626,   Loss Mean: 0.5828244686126709
Epoch: 9,   AUC: 0.7259122877330063,   Loss Mean: 0.5747462511062622
Epoch: 10,   AUC: 0.7352037062906013,   Loss Mean: 0.5676015615463257
Epoch: 11,   AUC: 0.7426657329838362,   Loss Mean: 0.5616015195846558
Epoch: 12,   AUC: 0.7488969951528721,   Loss Mean: 0.5564162135124207
Epoch: 13,   AUC: 0.754324121225936,   Loss Mean: 0.5519340634346008
Epoch: 14,   AUC: 0.7589823076117422,   Loss Mean: 0.5481910109519958
Epoch: 15,   AUC: 0.7629200394004094,   Loss Mean: 0.5448542237281799
Epoch: 16,   AUC: 0.7664166119302308,   Loss Mean: 0.5421968102455139
Epoch: 17,   AUC: 0.7693476406670166,   Loss Mean: 0.5396553874015808
Epoch: 18,   AUC: 0.7718043229176297,   Loss Mean: 0.537002444267273
Epoch: 19,   AUC: 0.7741349768498819,   Loss Mean: 0.5347164869308472
Epoch: 20,   AUC: 0.7761443605644545,   Loss Mean: 0.5328389406204224
Epoch: 21,   AUC: 0.7778080578771153,   Loss Mean: 0.531193733215332
Epoch: 22,   AUC: 0.7794976853062761,   Loss Mean: 0.53025883436203
Epoch: 23,   AUC: 0.781035036717045,   Loss Mean: 0.528741717338562
Epoch: 24,   AUC: 0.782240943661201,   Loss Mean: 0.527310311794281
Epoch: 25,   AUC: 0.7834673757622085,   Loss Mean: 0.5258097052574158
Epoch: 26,   AUC: 0.784560616048191,   Loss Mean: 0.5251953601837158
Epoch: 27,   AUC: 0.7854935591925936,   Loss Mean: 0.5241621136665344
Epoch: 28,   AUC: 0.7863903471380657,   Loss Mean: 0.5231839418411255
Epoch: 29,   AUC: 0.7874349850645751,   Loss Mean: 0.5219185948371887
Epoch: 30,   AUC: 0.7881321569134747,   Loss Mean: 0.5217874050140381
Epoch: 31,   AUC: 0.7888931796610479,   Loss Mean: 0.5203345417976379
Epoch: 32,   AUC: 0.7896320017595759,   Loss Mean: 0.5202598571777344
Epoch: 33,   AUC: 0.790265364987166,   Loss Mean: 0.5190582871437073
Epoch: 34,   AUC: 0.7909540249934757,   Loss Mean: 0.5188441872596741
Epoch: 35,   AUC: 0.7915410829316957,   Loss Mean: 0.5177248120307922
Epoch: 36,   AUC: 0.7920613280392625,   Loss Mean: 0.5174544453620911
Epoch: 37,   AUC: 0.7926653623522797,   Loss Mean: 0.5163199305534363
Epoch: 38,   AUC: 0.7931156263434136,   Loss Mean: 0.5156539678573608
Epoch: 39,   AUC: 0.7936501591867569,   Loss Mean: 0.5149373412132263
Epoch: 40,   AUC: 0.7941324301621434,   Loss Mean: 0.5153984427452087
Epoch: 41,   AUC: 0.7945311988141917,   Loss Mean: 0.5145834684371948
Epoch: 42,   AUC: 0.7949679561941765,   Loss Mean: 0.5134322047233582
Epoch: 43,   AUC: 0.795387660194166,   Loss Mean: 0.5130682587623596
Epoch: 44,   AUC: 0.7956529894066293,   Loss Mean: 0.5122935175895691
Epoch: 45,   AUC: 0.7961241167735256,   Loss Mean: 0.5111792087554932
Epoch: 46,   AUC: 0.796475841792242,   Loss Mean: 0.5113805532455444
Epoch: 47,   AUC: 0.7967807617427513,   Loss Mean: 0.5111795663833618
Epoch: 48,   AUC: 0.7971370809016735,   Loss Mean: 0.5103074908256531
Epoch: 49,   AUC: 0.7974084613134902,   Loss Mean: 0.5105810165405273
Epoch: 50,   AUC: 0.7977358813777055,   Loss Mean: 0.509635865688324
Epoch: 51,   AUC: 0.7979775121145182,   Loss Mean: 0.5080676674842834
Epoch: 52,   AUC: 0.7983483394554715,   Loss Mean: 0.5090319514274597
Epoch: 53,   AUC: 0.7985112240723797,   Loss Mean: 0.5086759924888611
Epoch: 54,   AUC: 0.7987279167008375,   Loss Mean: 0.5082783699035645
Epoch: 55,   AUC: 0.7990182011339224,   Loss Mean: 0.507624089717865
Epoch: 56,   AUC: 0.7993279779482558,   Loss Mean: 0.5072258114814758
Epoch: 57,   AUC: 0.7995554362054389,   Loss Mean: 0.5071216225624084
Epoch: 58,   AUC: 0.7997300548040259,   Loss Mean: 0.5071069598197937
Epoch: 59,   AUC: 0.8000196542431559,   Loss Mean: 0.5061677098274231
Epoch: 60,   AUC: 0.8001383539818125,   Loss Mean: 0.5060367584228516
Epoch: 61,   AUC: 0.8004209142398602,   Loss Mean: 0.5060011744499207
Epoch: 62,   AUC: 0.800552954500022,   Loss Mean: 0.5057827234268188
Epoch: 63,   AUC: 0.8007996313421923,   Loss Mean: 0.505217969417572
Epoch: 64,   AUC: 0.800912186267333,   Loss Mean: 0.5043762922286987
Epoch: 65,   AUC: 0.801155642480321,   Loss Mean: 0.5046355128288269
Epoch: 66,   AUC: 0.8013240669418008,   Loss Mean: 0.5045826435089111
Epoch: 67,   AUC: 0.8015022499248026,   Loss Mean: 0.5036026835441589
Epoch: 68,   AUC: 0.801632672069193,   Loss Mean: 0.5040364265441895
Epoch: 69,   AUC: 0.8017823958433926,   Loss Mean: 0.5038147568702698
Epoch: 70,   AUC: 0.8019622472723612,   Loss Mean: 0.5032134056091309
Epoch: 71,   AUC: 0.8020943318230946,   Loss Mean: 0.5030423402786255
Epoch: 72,   AUC: 0.8022738802642887,   Loss Mean: 0.5027927756309509
Epoch: 73,   AUC: 0.8023498552036525,   Loss Mean: 0.5024818778038025
Epoch: 74,   AUC: 0.8025275912545222,   Loss Mean: 0.5023679733276367
Epoch: 75,   AUC: 0.8026987204606851,   Loss Mean: 0.502577543258667
Epoch: 76,   AUC: 0.8027967229132232,   Loss Mean: 0.5016879439353943
Epoch: 77,   AUC: 0.802843173656857,   Loss Mean: 0.5016050934791565
Epoch: 78,   AUC: 0.8030888715767333,   Loss Mean: 0.5012237429618835
Epoch: 79,   AUC: 0.8031876893784315,   Loss Mean: 0.5009651184082031
Epoch: 80,   AUC: 0.8032720609042387,   Loss Mean: 0.5010382533073425
Epoch: 81,   AUC: 0.8034328140373861,   Loss Mean: 0.5001423954963684
Epoch: 82,   AUC: 0.8036077180081792,   Loss Mean: 0.49971818923950195
Epoch: 83,   AUC: 0.8036842012825132,   Loss Mean: 0.500150203704834
Epoch: 84,   AUC: 0.8037903169624966,   Loss Mean: 0.5002935528755188
Epoch: 85,   AUC: 0.8039136601649505,   Loss Mean: 0.49939027428627014
Epoch: 86,   AUC: 0.8040096504162895,   Loss Mean: 0.4999310374259949
Epoch: 87,   AUC: 0.804134322839195,   Loss Mean: 0.49981826543807983
Epoch: 88,   AUC: 0.8042306206080261,   Loss Mean: 0.4990226626396179
Epoch: 89,   AUC: 0.8043061148940269,   Loss Mean: 0.49869123101234436
Epoch: 90,   AUC: 0.8043983590689472,   Loss Mean: 0.49849623441696167
Epoch: 91,   AUC: 0.8044726081859219,   Loss Mean: 0.49865052103996277
Epoch: 92,   AUC: 0.804537269400736,   Loss Mean: 0.49880263209342957
Epoch: 93,   AUC: 0.8047323703755086,   Loss Mean: 0.49814048409461975
Epoch: 94,   AUC: 0.8048043792955009,   Loss Mean: 0.4978565275669098
Epoch: 95,   AUC: 0.8049212616108137,   Loss Mean: 0.49753180146217346
Epoch: 96,   AUC: 0.8049295525038475,   Loss Mean: 0.49718695878982544
Epoch: 97,   AUC: 0.8050615504866454,   Loss Mean: 0.4972480237483978
Epoch: 98,   AUC: 0.8051422720667063,   Loss Mean: 0.497586190700531
Epoch: 99,   AUC: 0.8052240002506685,   Loss Mean: 0.4966777265071869
Epoch: 100,   AUC: 0.8052867871690181,   Loss Mean: 0.49698129296302795

Return code: 0

Experiment completed.
Best AUC:   0.805287
Best Epoch: 100
Final AUC:  0.805287

   Experiment  Learning Rate    d  Best AUC  Best Epoch  Final AUC
0           1         0.0010   65  0.807554          34   0.801294
1           2         0.0010  125  0.808607          19   0.787771
2           3         0.0005   65  0.807989          63   0.807061
3           4         0.0005  125  0.809417          27   0.797855
4           5         0.0001   65  0.805287         100   0.805287

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

======================================================================
EXPERIMENT 6/6
Learning rate: 0.0001
Embedding dimension (d): 125
======================================================================
/content/knowledge-tracing-collection-pytorch/models/utils.py:91: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:78.)
  q_seqs.append(FloatTensor(q_seq[:-1]))
Epoch: 1,   AUC: 0.54824959563916,   Loss Mean: 0.678837239742279
Epoch: 2,   AUC: 0.6234278518022655,   Loss Mean: 0.6332276463508606
Epoch: 3,   AUC: 0.6823338163595973,   Loss Mean: 0.610404908657074
Epoch: 4,   AUC: 0.7165793915583523,   Loss Mean: 0.5895418524742126
Epoch: 5,   AUC: 0.7366851071334171,   Loss Mean: 0.5725151896476746
Epoch: 6,   AUC: 0.7505282279798069,   Loss Mean: 0.5594024062156677
Epoch: 7,   AUC: 0.7603162792339515,   Loss Mean: 0.5496392250061035
Epoch: 8,   AUC: 0.7675392440435301,   Loss Mean: 0.5423813462257385
Epoch: 9,   AUC: 0.7729503273669155,   Loss Mean: 0.5360283851623535
Epoch: 10,   AUC: 0.7773976146330187,   Loss Mean: 0.5321010947227478
Epoch: 11,   AUC: 0.7810440624309268,   Loss Mean: 0.5277618169784546
Epoch: 12,   AUC: 0.7838510544151708,   Loss Mean: 0.5244458317756653
Epoch: 13,   AUC: 0.7865192946077405,   Loss Mean: 0.5221375823020935
Epoch: 14,   AUC: 0.7886198776423836,   Loss Mean: 0.5196366906166077
Epoch: 15,   AUC: 0.790669281914868,   Loss Mean: 0.5169354677200317
Epoch: 16,   AUC: 0.7922530357522837,   Loss Mean: 0.5152683258056641
Epoch: 17,   AUC: 0.7937025549330323,   Loss Mean: 0.512994647026062
Epoch: 18,   AUC: 0.7950164840649611,   Loss Mean: 0.5120769739151001
Epoch: 19,   AUC: 0.7962066487307031,   Loss Mean: 0.5107538104057312
Epoch: 20,   AUC: 0.7972271714475467,   Loss Mean: 0.5095558762550354
Epoch: 21,   AUC: 0.7978268431392551,   Loss Mean: 0.5079060792922974
Epoch: 22,   AUC: 0.7986029277010049,   Loss Mean: 0.50667804479599
Epoch: 23,   AUC: 0.7996789902914101,   Loss Mean: 0.5058587789535522
Epoch: 24,   AUC: 0.8003518415834481,   Loss Mean: 0.5047505497932434
Epoch: 25,   AUC: 0.8008635647823857,   Loss Mean: 0.5040369629859924
Epoch: 26,   AUC: 0.8014240921648786,   Loss Mean: 0.5033265352249146
Epoch: 27,   AUC: 0.8019126584410646,   Loss Mean: 0.5022093653678894
Epoch: 28,   AUC: 0.8022805797165546,   Loss Mean: 0.5020656585693359
Epoch: 29,   AUC: 0.8028618678012118,   Loss Mean: 0.5006585717201233
Epoch: 30,   AUC: 0.803003153214906,   Loss Mean: 0.5002756118774414
Epoch: 31,   AUC: 0.803490139122967,   Loss Mean: 0.49951714277267456
Epoch: 32,   AUC: 0.803793895439366,   Loss Mean: 0.4993514120578766
Epoch: 33,   AUC: 0.8040148686509144,   Loss Mean: 0.49859344959259033
Epoch: 34,   AUC: 0.8043882864870078,   Loss Mean: 0.4985940456390381
Epoch: 35,   AUC: 0.8047417312884897,   Loss Mean: 0.49761366844177246
Epoch: 36,   AUC: 0.8047697259495916,   Loss Mean: 0.4972059428691864
Epoch: 37,   AUC: 0.8051643931940434,   Loss Mean: 0.4964887797832489
Epoch: 38,   AUC: 0.8050916937437749,   Loss Mean: 0.49631813168525696
Epoch: 39,   AUC: 0.8054079510740254,   Loss Mean: 0.49533095955848694
Epoch: 40,   AUC: 0.8056059747232258,   Loss Mean: 0.4957413375377655
Epoch: 41,   AUC: 0.8058915185552371,   Loss Mean: 0.494599312543869
Epoch: 42,   AUC: 0.8061091020281475,   Loss Mean: 0.49387770891189575
Epoch: 43,   AUC: 0.8062039895449125,   Loss Mean: 0.4948951005935669
Epoch: 44,   AUC: 0.8061740642175279,   Loss Mean: 0.4929395914077759
Epoch: 45,   AUC: 0.8065468473898616,   Loss Mean: 0.4929623603820801
Epoch: 46,   AUC: 0.8067660479719396,   Loss Mean: 0.4926901161670685
Epoch: 47,   AUC: 0.806592455102728,   Loss Mean: 0.49272626638412476
Epoch: 48,   AUC: 0.8069264382243804,   Loss Mean: 0.49209722876548767
Epoch: 49,   AUC: 0.806993379900333,   Loss Mean: 0.4918898940086365
Epoch: 50,   AUC: 0.8072275849201652,   Loss Mean: 0.49151191115379333
Epoch: 51,   AUC: 0.807391364911244,   Loss Mean: 0.49070650339126587
Epoch: 52,   AUC: 0.8074689911843079,   Loss Mean: 0.49072667956352234
Epoch: 53,   AUC: 0.8073815263647117,   Loss Mean: 0.4906669557094574
Epoch: 54,   AUC: 0.807524456065879,   Loss Mean: 0.4905570447444916
Epoch: 55,   AUC: 0.8075933178387734,   Loss Mean: 0.48981544375419617
Epoch: 56,   AUC: 0.8076954302550409,   Loss Mean: 0.48945707082748413
Epoch: 57,   AUC: 0.8077608917199566,   Loss Mean: 0.4896647036075592
Epoch: 58,   AUC: 0.8078703765031978,   Loss Mean: 0.4889023005962372
Epoch: 59,   AUC: 0.8079383413920163,   Loss Mean: 0.4886755347251892
Epoch: 60,   AUC: 0.8080519477149319,   Loss Mean: 0.48895835876464844
Epoch: 61,   AUC: 0.8081738202690857,   Loss Mean: 0.4881071448326111
Epoch: 62,   AUC: 0.8079941414726863,   Loss Mean: 0.4881886839866638
Epoch: 63,   AUC: 0.8085006036563334,   Loss Mean: 0.4884131848812103
Epoch: 64,   AUC: 0.8082504671165537,   Loss Mean: 0.4876108765602112
Epoch: 65,   AUC: 0.8084698816019608,   Loss Mean: 0.486987441778183
Epoch: 66,   AUC: 0.8084557846176235,   Loss Mean: 0.48707717657089233
Epoch: 67,   AUC: 0.8085357336291901,   Loss Mean: 0.4863634407520294
Epoch: 68,   AUC: 0.808682166815236,   Loss Mean: 0.4865288734436035
Epoch: 69,   AUC: 0.8087976554874473,   Loss Mean: 0.48721787333488464
Epoch: 70,   AUC: 0.8088908488898463,   Loss Mean: 0.48565560579299927
Epoch: 71,   AUC: 0.808779965933786,   Loss Mean: 0.4857443869113922
Epoch: 72,   AUC: 0.8089165993275499,   Loss Mean: 0.4855146110057831
Epoch: 73,   AUC: 0.8087591065844393,   Loss Mean: 0.4856816232204437
Epoch: 74,   AUC: 0.8089707697165036,   Loss Mean: 0.48514825105667114
Epoch: 75,   AUC: 0.8089452608637364,   Loss Mean: 0.48546576499938965
Epoch: 76,   AUC: 0.8090409204456939,   Loss Mean: 0.48418015241622925
Epoch: 77,   AUC: 0.8089963022244625,   Loss Mean: 0.4844316244125366
Epoch: 78,   AUC: 0.8090864179354331,   Loss Mean: 0.48413756489753723
Epoch: 79,   AUC: 0.8091353192562649,   Loss Mean: 0.4837399423122406
Epoch: 80,   AUC: 0.809010548689479,   Loss Mean: 0.4836365282535553
Epoch: 81,   AUC: 0.8091677681396304,   Loss Mean: 0.48360341787338257
Epoch: 82,   AUC: 0.8092552138337525,   Loss Mean: 0.4831998348236084
Epoch: 83,   AUC: 0.8093108297059086,   Loss Mean: 0.4829842150211334
Epoch: 84,   AUC: 0.8093908733382418,   Loss Mean: 0.4829689562320709
Epoch: 85,   AUC: 0.8093015634136944,   Loss Mean: 0.4832674562931061
Epoch: 86,   AUC: 0.8093423545268927,   Loss Mean: 0.48211172223091125
Epoch: 87,   AUC: 0.8093685050896471,   Loss Mean: 0.48249077796936035
Epoch: 88,   AUC: 0.8094556095450467,   Loss Mean: 0.4820694923400879
Epoch: 89,   AUC: 0.8093592584262088,   Loss Mean: 0.48166587948799133
Epoch: 90,   AUC: 0.8093397348402391,   Loss Mean: 0.48127174377441406
Epoch: 91,   AUC: 0.8095053871145745,   Loss Mean: 0.48152875900268555
Epoch: 92,   AUC: 0.8093895179460887,   Loss Mean: 0.48181387782096863
Epoch: 93,   AUC: 0.8095485402238275,   Loss Mean: 0.48105865716934204
Epoch: 94,   AUC: 0.8096465668348591,   Loss Mean: 0.4804878830909729
Epoch: 95,   AUC: 0.8093835195934402,   Loss Mean: 0.4805915951728821
Epoch: 96,   AUC: 0.8095277145957115,   Loss Mean: 0.4802986979484558
Epoch: 97,   AUC: 0.8097847181873064,   Loss Mean: 0.4807959198951721
Epoch: 98,   AUC: 0.8096365732713261,   Loss Mean: 0.48077255487442017
Epoch: 99,   AUC: 0.8094737792487687,   Loss Mean: 0.4798976182937622
Epoch: 100,   AUC: 0.8097231205714662,   Loss Mean: 0.4794941842556

Return code: 0

Experiment completed.
Best AUC:   0.809785
Best Epoch: 97
Final AUC:  0.809723

   Experiment  Learning Rate    d  Best AUC  Best Epoch  Final AUC
0           1         0.0010   65  0.807554          34   0.801294
1           2         0.0010  125  0.808607          19   0.787771
2           3         0.0005   65  0.807989          63   0.807061
3           4         0.0005  125  0.809417          27   0.797855
4           5         0.0001   65  0.805287         100   0.805287
5           6         0.0001  125  0.809785          97   0.809723

Results saved to: /content/drive/MyDrive/education-ml-research/sakt_hyperparameter_results.csv

Original config.json restored.

## Hyperparameter Tuning Results

Six SAKT configurations were evaluated on the ASSISTments 2009 dataset by varying the learning rate and embedding dimension (d). The learning rates tested were 0.001, 0.0005, and 0.0001, while the embedding dimensions tested were 65 and 125. All other hyperparameters were kept constant, including a batch size of 128, 100 training epochs, sequence length of 100, Adam optimization, 5 attention heads, and 0.2 dropout.

The best-performing configuration was a learning rate of 0.0001 with an embedding dimension of 125, achieving a best AUC of 0.809785 at epoch 97. The final AUC for this configuration was 0.809723, indicating that performance remained highly stable through the end of training. The second-best configuration used a learning rate of 0.0005 with d = 125, achieving a best AUC of 0.809417 at epoch 27. The remaining configurations achieved best AUC values ranging from 0.805287 to 0.808607.

Based on these results, the configuration with a learning rate of 0.0001 and d = 125 was selected as the best-performing SAKT model for subsequent analysis. This configuration provided the highest observed AUC among all six experiments.

An important observation was that the final AUC was sometimes lower than the best AUC reached during training. For example, the learning rate of 0.001 with d = 125 achieved a best AUC of 0.808607 at epoch 19 but finished with an AUC of 0.787771. This demonstrates that continued training does not necessarily improve predictive performance, even when training loss may continue to decrease. Therefore, the highest AUC achieved during training and its corresponding epoch were used to identify the best-performing configuration.

## SAKT Performance Compared with Published Results

The best-performing SAKT configuration in this study achieved an AUC of 0.809785 on the ASSISTments 2009 dataset. This result is very close to the 0.8106 ± 0.0008 AUC reported for SAKT on ASSISTment2009 by the PyTorch implementation used as a reference for this project. The repository reports SAKT with n = 100, d = 100, 5 attention heads, and 0.2 dropout.

The difference between the current result and that PyTorch benchmark is only 0.000815 AUC, or 0.0815 percentage points. Thus, the model's performance is well within a 2-percentage-point difference from the independently reported PyTorch implementation. The original SAKT paper reports a higher AUC of approximately 0.848 on ASSIST2009, but replication studies and implementations show that SAKT performance can vary substantially depending on implementation, preprocessing, and train/test methodology.

Overall, the 0.809785 AUC obtained in this study provides strong evidence that the implementation is functioning comparably to an established PyTorch SAKT implementation, making it a reasonable model to use for the subsequent reliability analysis. The reference implementation is available in the knowledge-tracing-collection-pytorch GitHub repository.